import { beforeEach, describe, expect, it, vi } from 'vitest';
import {
  checkForUpdates,
  compareVersions,
  getPreferredInstallAsset,
  installUpdateFromRelease,
  normalizeVersion,
} from './updateService';
import { AppUpdateInfo, ReleaseAsset } from '../types/update';

vi.mock('@tauri-apps/plugin-updater', () => ({
  check: vi.fn(),
}));

vi.mock('@tauri-apps/plugin-process', () => ({
  relaunch: vi.fn(),
}));

describe('update service', () => {
  beforeEach(() => {
    vi.useRealTimers();
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
    if (typeof window !== 'undefined') {
      delete (window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__;
    }
  });

  it('compares semantic versions numerically', () => {
    expect(compareVersions('0.10.0', '0.2.0')).toBe(1);
    expect(compareVersions('v1.0.0', '1.0.0')).toBe(0);
    expect(compareVersions('1.0.0-beta.1', '1.0.0')).toBe(-1);
  });

  it('normalizes release tags to app versions', () => {
    expect(normalizeVersion('v0.2.0')).toBe('0.2.0');
    expect(normalizeVersion('taskmanager-v1.4.3')).toBe('1.4.3');
  });

  it('maps GitHub latest release responses to update info', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => ({
      ok: true,
      status: 200,
      json: async () => ({
        tag_name: 'v0.2.0',
        name: 'TaskManager v0.2.0',
        html_url: 'https://github.com/smileQiny/taskmanager/releases/tag/v0.2.0',
        published_at: '2026-05-29T00:00:00Z',
        assets: [
          {
            name: 'TaskManager_0.2.0_aarch64.dmg',
            browser_download_url: 'https://example.com/app.dmg',
            size: 1024,
            content_type: 'application/octet-stream',
          },
          {
            name: 'latest.json',
            browser_download_url: 'https://example.com/latest.json',
            size: 200,
            content_type: 'application/json',
          },
        ],
      }),
    } as Response)));

    const info = await checkForUpdates({
      currentVersion: '0.1.0',
      apiUrl: 'https://example.com/latest-release',
    });

    expect(info.isUpdateAvailable).toBe(true);
    expect(info.latestVersion).toBe('0.2.0');
    expect(info.assets).toHaveLength(1);
    expect(info.preferredAsset?.downloadUrl).toBe('https://example.com/app.dmg');
  });

  it('maps signed updater latest.json responses without using the GitHub REST API shape', async () => {
    vi.stubGlobal('navigator', {
      platform: 'Win32',
      userAgent: 'Windows',
    });
    const fetch = vi.fn(async () => ({
      ok: true,
      status: 200,
      json: async () => ({
        version: '0.2.5',
        notes: 'TaskManager desktop installers generated by GitHub Actions.',
        pub_date: '2026-06-22T07:25:19.025Z',
        platforms: {
          'darwin-aarch64': {
            signature: 'signed',
            url: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.5/Task.Manager_aarch64.app.tar.gz',
          },
          'windows-x86_64': {
            signature: 'signed',
            url: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.5/Task.Manager_0.2.5_x64-setup.exe',
          },
          'linux-x86_64': {
            signature: 'signed',
            url: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.5/Task.Manager_0.2.5_amd64.AppImage',
          },
        },
      }),
    } as Response));
    vi.stubGlobal('fetch', fetch);

    const info = await checkForUpdates({
      currentVersion: '0.2.4',
      apiUrl: 'https://example.com/latest.json',
    });

    expect(fetch).toHaveBeenCalledWith('https://example.com/latest.json', expect.objectContaining({
      headers: expect.objectContaining({ Accept: 'application/json' }),
    }));
    expect(info.latestVersion).toBe('0.2.5');
    expect(info.releaseName).toBe('TaskManager v0.2.5');
    expect(info.releaseUrl).toBe('https://github.com/smileQiny/taskmanager/releases/tag/v0.2.5');
    expect(info.publishedAt).toBe('2026-06-22T07:25:19.025Z');
    expect(info.assets.map((asset) => asset.name)).toEqual([
      'Task.Manager_aarch64.app.tar.gz',
      'Task.Manager_0.2.5_x64-setup.exe',
      'Task.Manager_0.2.5_amd64.AppImage',
    ]);
    expect(info.preferredAsset?.name).toBe('Task.Manager_0.2.5_x64-setup.exe');
    expect(info.isUpdateAvailable).toBe(true);
  });

  it('uses the native signed updater check inside Tauri', async () => {
    const { check } = await import('@tauri-apps/plugin-updater');
    vi.stubGlobal('window', { __TAURI_INTERNALS__: {} });
    vi.mocked(check).mockResolvedValue({
      currentVersion: '0.2.4',
      version: '0.2.5',
      date: '2026-06-22T08:00:00Z',
      body: 'Desktop updater release.',
      rawJson: {
        platforms: {
          'darwin-aarch64': {
            signature: 'signed',
            url: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.5/Task.Manager_aarch64.app.tar.gz',
          },
          'windows-x86_64': {
            signature: 'signed',
            url: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.5/Task.Manager_0.2.5_x64-setup.exe',
          },
        },
      },
    } as unknown as Awaited<ReturnType<typeof check>>);
    vi.stubGlobal('fetch', vi.fn());

    const info = await checkForUpdates({ currentVersion: '0.2.4' });

    expect(check).toHaveBeenCalled();
    expect(fetch).not.toHaveBeenCalled();
    expect(info.latestVersion).toBe('0.2.5');
    expect(info.releaseUrl).toBe('https://github.com/smileQiny/taskmanager/releases/tag/v0.2.5');
    expect(info.assets).toHaveLength(2);
    expect(info.isUpdateAvailable).toBe(true);
  });

  it('falls back to latest.json when the native updater check does not finish', async () => {
    const { check } = await import('@tauri-apps/plugin-updater');
    vi.stubGlobal('window', { __TAURI_INTERNALS__: {} });
    vi.mocked(check).mockReturnValue(new Promise(() => undefined) as ReturnType<typeof check>);
    const fetch = vi.fn(async () => ({
      ok: true,
      status: 200,
      json: async () => ({
        version: '0.2.8',
        pub_date: '2026-06-23T01:00:00Z',
        platforms: {
          'darwin-aarch64': {
            signature: 'signed',
            url: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.8/Task.Manager_aarch64.app.tar.gz',
          },
        },
      }),
    } as Response));
    vi.stubGlobal('fetch', fetch);

    const infoPromise = checkForUpdates({
      currentVersion: '0.2.7',
      nativeTimeoutMs: 1,
    });
    const info = await infoPromise;

    expect(check).toHaveBeenCalled();
    expect(fetch).toHaveBeenCalledWith(
      'https://github.com/smileQiny/taskmanager/releases/latest/download/latest.json',
      expect.objectContaining({
        headers: expect.objectContaining({ Accept: 'application/json' }),
      }),
    );
    expect(info.latestVersion).toBe('0.2.8');
    expect(info.isUpdateAvailable).toBe(true);
  });

  it('selects a platform installer when possible', () => {
    vi.stubGlobal('navigator', {
      platform: 'MacIntel',
      userAgent: 'Mac OS',
    });

    const assets: ReleaseAsset[] = [
      { name: 'TaskManager_0.2.0_x64.msi', downloadUrl: 'https://example.com/app.msi', size: 1 },
      { name: 'TaskManager_0.2.0_aarch64.dmg', downloadUrl: 'https://example.com/app.dmg', size: 1 },
    ];

    expect(getPreferredInstallAsset(assets)?.name).toBe('TaskManager_0.2.0_aarch64.dmg');
  });

  it('uses Tauri signed updater inside Tauri', async () => {
    const { check } = await import('@tauri-apps/plugin-updater');
    const { relaunch } = await import('@tauri-apps/plugin-process');
    const downloadAndInstall = vi.fn().mockResolvedValue(undefined);
    vi.mocked(check).mockResolvedValue({
      downloadAndInstall,
    } as unknown as Awaited<ReturnType<typeof check>>);
    vi.stubGlobal('window', { __TAURI_INTERNALS__: {} });

    const release = makeRelease();
    const result = await installUpdateFromRelease(release);

    expect(check).toHaveBeenCalled();
    expect(downloadAndInstall).toHaveBeenCalled();
    expect(relaunch).toHaveBeenCalled();
    expect(result.action).toBe('installed');
  });

  it('opens the release page in browser previews', async () => {
    const { check } = await import('@tauri-apps/plugin-updater');
    const open = vi.fn();
    vi.stubGlobal('open', open);
    vi.stubGlobal('window', undefined);

    const result = await installUpdateFromRelease(makeRelease());

    expect(check).not.toHaveBeenCalled();
    expect(open).toHaveBeenCalledWith(
      'https://github.com/smileQiny/taskmanager/releases/tag/v0.2.2',
      '_blank',
      'noopener,noreferrer',
    );
    expect(result.action).toBe('opened');
  });

  it('opens the release page when the native install check times out', async () => {
    const { check } = await import('@tauri-apps/plugin-updater');
    const open = vi.fn();
    vi.stubGlobal('window', {
      __TAURI_INTERNALS__: {},
      open,
    });
    vi.mocked(check).mockReturnValue(new Promise(() => undefined) as ReturnType<typeof check>);

    const result = await installUpdateFromRelease(makeRelease(), { nativeTimeoutMs: 1 });

    expect(check).toHaveBeenCalled();
    expect(open).toHaveBeenCalledWith(
      'https://github.com/smileQiny/taskmanager/releases/tag/v0.2.2',
      '_blank',
      'noopener,noreferrer',
    );
    expect(result.action).toBe('opened');
    expect(result.message).toContain('自动更新未完成');
  });
});

function makeRelease(): AppUpdateInfo {
  return {
    currentVersion: '0.2.1',
    latestVersion: '0.2.2',
    releaseName: 'TaskManager v0.2.2',
    releaseUrl: 'https://github.com/smileQiny/taskmanager/releases/tag/v0.2.2',
    publishedAt: '2026-06-22T05:47:00Z',
    assets: [
      {
        name: 'Task.Manager_0.2.2_aarch64.dmg',
        downloadUrl: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.2/Task.Manager_0.2.2_aarch64.dmg',
        size: 1,
      },
    ],
    preferredAsset: {
      name: 'Task.Manager_0.2.2_aarch64.dmg',
      downloadUrl: 'https://github.com/smileQiny/taskmanager/releases/download/v0.2.2/Task.Manager_0.2.2_aarch64.dmg',
      size: 1,
    },
    isUpdateAvailable: true,
    checkedAt: '2026-06-22T05:48:00Z',
  };
}
